---
  # Refer to docs/javascript/README.md for detail
  extends: airbnb

  env:
    worker: true
    node: false

  rules:
    react/jsx-filename-extension: off
    no-restricted-globals: off
    linebreak-style: off
    import/prefer-default-export: off
