---
# Refer to docs/javascript/README.md for detail
extends:
  - daojs
  - "plugin:lodash/canonical"

globals:
  onmessage: true
  postMessage: true

rules:
  import/prefer-default-export: off
  no-var: error
