---
# Refer to docs/javascript/README.md for detail
extends:
  - airbnb
  - "plugin:react/recommended"
  - "plugin:lodash/canonical"

globals:
  onmessage: true
  postMessage: true

env:
  es6: true

parser: babel-eslint

rules:
  import/prefer-default-export: off
  no-var: error
