---
# Refer to docs/javascript/README.md for detail
extends:
  - airbnb
  - "plugin:react/recommended"
  - "plugin:lodash/canonical"

env:
  es6: true
  browser: true

parser: babel-eslint

rules:
  linebreak-style: off
  no-var: error
  react/jsx-filename-extension: off

plugins:
  - lodash
