---
# Refer to docs/javascript/README.md for detail
extends:
  - airbnb
  - "plugin:react/recommended"

env:
  es6: true

parser: babel-eslint

rules:
  linebreak-style: off
  no-var: error
  react/jsx-filename-extension: off
