---
# Refer to docs/javascript/README.md for detail
extends:
  - daojs
  - "plugin:lodash/canonical"

env:
  es6: true
  browser: true

parser: babel-eslint

rules:
  no-var: error
  react/jsx-filename-extension: off
  jsx-a11y/anchor-is-valid:
  - error
  - components:
    - Link
    specialLink:
    - to

plugins:
  - lodash
